# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.5
  - nightly
env:
  - PYTHON=""
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
before_install: julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/DrChainsaw/BaseOnnx.jl", rev="onnxmutable"));' 
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
